[package]
name = "tih-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
rand = "0.8.5"
ratatui = "0.29.0"
reqwest = {version = "0.12.9", features = ["json"]}
serde_json = "1.0.132"
tokio = {version = "1.41.1", features = ["full"]}
